Feature/electrical meter
progetto-oop-22-23/OOP22-HOMER pull request #64
Opened 2023-03-07 16:43 UTC by aleemont1

This PR introduces a basic Electrical Meter.

2023-03-07 16:52 UTC, aleemont1 commented
This is a very basic implementation. It doesn't take count of the amount of time an outlet has been consuming power. It cuts power to the most-consuming outlet in the very moment the global consumption is equal to the global max consumption value. 

In the next updates I want to implement the following features:

- Checking the average consumption in the last n. ticks of the simulation (of a single outlet and of all the outlets, too).
- Cutting the power if the average consumption of the last n. ticks is above the max power.

But still idk how to do so, I'll study the clock class already implemented but I'll listen for advice.

2023-03-07 21:33 UTC, smagnaniuni commented
> This is a very basic implementation. It doesn't take count of the amount of time an outlet has been consuming power. It cuts power to the most-consuming outlet in the very moment the global consumption is equal to the global max consumption value.
> 
> In the next updates I want to implement the following features:
> 
>     * Checking the average consumption in the last n. ticks of the simulation (of a single outlet and of all the outlets, too).
> 
>     * Cutting the power if the average consumption of the last n. ticks is above the max power.
> 
> 
> But still idk how to do so, I'll study the clock class already implemented but I'll listen for advice.
> 
> For a more advanced level i think I might need to check wether the derivative of the average consumption in the last tick is positive (The consumption is rising) or negative (The consumption is decreasing), but I'll see.
> 
> Maybe it should be done from the main controller, in the main loop, I'll think of it.

For simulation matters see #49 
Each device could implement a SimElement interface with an updateTick(dt) / updateStep(dt) / however we want to call it.
In there the deltas/steps/derivatives can be multiplied by the time difference and get the actual value out.
The controller would also implement it.
All of the updateTicks would be called from the simulation side (our "game" loop)

2023-03-09 14:27 UTC, aleemont1 commented
I think it will need refactoring due to last changes to interfaces, I'll check and do it asap.

2023-03-11 16:18 UTC, aleemont1 commented
Please give me a feedback otherwise I'm stuck with this.

2023-03-11 16:28 UTC, michelececcacci commented
didn't you say you needed to do a refactor?

2023-03-11 16:37 UTC, michelececcacci requested changes

2023-03-11 16:37 UTC, michelececcacci commented on app/src/main/java/homer/controller/api/electricalmeter/ElectricalMeter.java
> +    void sortForConsumption();
not sure we need something like this, honestly.  I don't see the point of having this public

2023-03-11 16:37 UTC, michelececcacci commented on app/src/main/java/homer/controller/impl/electricalmeter/ElectricalMeterImpl.java
> +    public void computeConsumption() {
i think this can be done in a nicer way with streams

2023-03-11 16:37 UTC, michelececcacci commented on app/src/main/java/homer/controller/impl/electricalmeter/ElectricalMeterImpl.java
> +    public void removeOutlet(final Outlet outlet) {
shouldn't this be marked with a `throws` clause?

2023-03-12 16:17 UTC, aleemont1 commented
I noticed you changed the directory structure, is it necessary for me to do the same in this pr? Should I just create the new dir structure or merge from dev?

2023-03-12 16:19 UTC, michelececcacci commented
As i said before, `computeconsumption` can be more readable by  using streams.

2023-03-12 16:19 UTC, michelececcacci commented
>I noticed you changed the directory structure, is it necessary for me to do the same in this pr? Should I just create the new dir structure or merge from dev?

you need to merge, otherwise we can't track changes

2023-03-12 16:21 UTC, michelececcacci requested changes
upstream changes need to be merged

2023-03-12 17:15 UTC, aleemont1 commented
Done. Should be ok now. I'll wait for your review.

2023-03-12 17:53 UTC, aleemont1 commented
> For simulation matters see #49 Each device could implement a SimElement interface with an updateTick(dt) / updateStep(dt) / however we want to call it. In there the deltas/steps/derivatives can be multiplied by the time difference and get the actual value out. The controller would also implement it. All of the updateTicks would be called from the simulation side (our "game" loop)

So ElectricalMeter should extend DiscreteObject, and Override the updateTick method, in which I'd basically call "checkConsumption", right?

2023-03-12 20:41 UTC, michelececcacci commented
Should be good. please fix CI errors.

2023-03-13 09:00 UTC, aleemont1 commented
> Should be good. please fix CI errors and assign `"COUTLET"` and `"LOUTLET"` to a variable each in the unit tests

Should I assign constants for every number I used in tests? That seems a bit odd. Can we write a post on the forum to ask if somebody has solved this linter issue? Or maybe just to know if it's ok to suppress this warning on test classes.

2023-03-13 09:02 UTC, aleemont1 commented
@michelececcacci 
https://github.com/checkstyle/checkstyle/issues/2584

2023-03-13 20:50 UTC, michelececcacci commented
should be good. Please verify that checkstyle passes

2023-03-14 11:36 UTC, michelececcacci commented
LGTM

2023-03-15 10:27 UTC, michelececcacci commented
please resolve merge conflicts before asking for reviews

2023-03-15 11:35 UTC, aleemont1 commented
DON'T MERGE BEFORE MERGING Outlets

2023-03-15 13:24 UTC, aleemont1 commented
> 

Done. I think you can resolve this. IDKW it looks CI checks haven't been running since that change request.

2023-03-15 13:25 UTC, aleemont1 commented
> upstream changes need to be merged

Done. Looks like CI checks haven't been running since this change request, and I can't resolve the conversation. Can you do it?

2023-03-15 15:34 UTC, michelececcacci commented
still merge conflicts

2023-03-15 15:57 UTC, aleemont1 commented
> still merge conflicts

Yep, probably due to last feature/Outlets merge, I'll fix it asap.

2023-03-15 23:25 UTC, aleemont1 commented
CI is now passing, I'm merging this.

2023-03-15 23:26 UTC, merged